spring.application.name=service-discovery-hub
server.port=7080

eureka.client.registerWithEureka=false  
eureka.client.fetchRegistry=false       
eureka.server.enableSelfPreservation=true  
eureka.server.evictionIntervalTimerInMs=60000